try:
    # C贸digo que puede lanzar una excepci贸n
    resultado = 10 / 0
except ZeroDivisionError as e:
    # Captura la excepci贸n y la almacena en la variable 'e'
    print(f"Ocurri贸 un error: {e}")